import { FONTS, LIST_STYLES } from '../lib/defaults.js'

export const SITE_FIELDS = [
  { type: 'heading', label: '기본 정보' },
  { key: 'title', label: '사이트 이름' },
  { key: 'description', label: '한 줄 소개' },
  { key: 'favicon', label: '파비콘 (이모지 또는 이미지 주소)', placeholder: '💌' },
  { key: 'footer', label: '하단 문구 (비우면 © 연도 사이트 이름)' },

  { type: 'heading', label: '드림 페어 프로필', help: '프로필 위젯, 이름 변환({{나}}, {{상대}}), 디데이에 쓰여요.' },
  { key: 'pair.pairName', label: '페어 이름', placeholder: '나 × 최애' },
  { key: 'pair.bio', label: '소개글', type: 'textarea', rows: 2 },
  { key: 'pair.symbol', label: '두 사람 사이 아이콘', type: 'icon' },
  { key: 'pair.symbolColor', label: '두 사람 사이 아이콘 색 (비우면 포인트 색)', type: 'color' },
  { key: 'pair.symbolBg', label: '두 사람 사이 아이콘 바탕색 (비우면 카드 색)', type: 'color' },
  { key: 'pair.startDate', label: '시작일 (사귄 날 · 드림 시작일)', type: 'date' },
  { key: 'pair.startLabel', label: '시작일 문구', placeholder: '함께한 지' },
  { key: 'pair.me.name', label: '나 — 이름' },
  { key: 'pair.me.sub', label: '나 — 아이디 / 한 줄' },
  { key: 'pair.me.image', label: '나 — 프로필 사진', type: 'image', guide: 'avatar' },
  { key: 'pair.me.color', label: '나 — 테두리 색', type: 'color' },
  { key: 'pair.partner.name', label: '상대 — 이름' },
  { key: 'pair.partner.sub', label: '상대 — 아이디 / 한 줄' },
  { key: 'pair.partner.image', label: '상대 — 프로필 사진', type: 'image', guide: 'avatar' },
  { key: 'pair.partner.color', label: '상대 — 테두리 색', type: 'color' },

  { type: 'heading', label: '메뉴' },
  { key: 'menu.archive', label: '서랍 메뉴에 "전체 기록" 보이기', type: 'toggle' },
  { key: 'menu.notice', label: '공지사항 아이콘', type: 'toggle' },
  { key: 'menu.guestbook', label: '방명록 아이콘', type: 'toggle' },
  { key: 'menu.tags', label: '태그 아이콘', type: 'toggle' },
  { key: 'menu.calendar', label: '캘린더 아이콘', type: 'toggle' },
  { key: 'menu.banners', label: '배너 아이콘', type: 'toggle' },
  {
    key: 'bottomNav',
    label: '하단 탭 메뉴 (디자인 > 배치에서 하단 탭을 켜면 보여요)',
    type: 'list',
    itemLabel: '탭',
    itemFields: [
      { key: 'label', label: '이름' },
      { key: 'href', label: '주소', placeholder: '/archive' },
      { key: 'icon', label: '아이콘', type: 'icon' },
    ],
  },
  {
    key: 'links',
    label: '외부 링크',
    type: 'list',
    itemLabel: '링크',
    itemFields: [
      { key: 'name', label: '이름' },
      { key: 'url', label: '주소' },
      { key: 'icon', label: '아이콘', type: 'icon' },
    ],
  },

  { type: 'heading', label: 'BGM', help: '유튜브 주소를 넣으면 서랍 메뉴와 BGM 위젯에서 재생돼요.' },
  { key: 'bgmLabel', label: '재생 중 문구', placeholder: 'Now playing' },
  { key: 'bgmPreload', label: '접속하면 BGM 미리 준비하기', type: 'toggle', help: '소리는 나지 않고, 재생 버튼을 누르면 바로 시작돼요.' },
  {
    key: 'bgmAutoplay',
    label: '첫 클릭·터치 때 BGM 자동 재생',
    type: 'toggle',
    help: '브라우저 규칙상 방문자가 한 번 누르기 전에는 소리를 낼 수 없어서, 처음 누를 때 시작해요. 유튜브 프리미엄으로 다른 탭에서 음악을 듣는 사람은 이 사이트 재생이 시작되면 그쪽이 멈출 수 있어서 기본은 꺼둬요.',
  },
  {
    key: 'bgm',
    label: '곡 목록',
    type: 'list',
    itemLabel: '곡',
    itemFields: [
      { key: 'title', label: '제목' },
      { key: 'url', label: '유튜브 주소' },
    ],
  },

  { type: 'heading', label: '기능' },
  { key: 'features.comments', label: '글 댓글', type: 'toggle' },
  { key: 'features.guestbook', label: '방명록', type: 'toggle' },
  { key: 'guestbookIntro', label: '방명록 안내 문구' },
  { key: 'features.reactions', label: '글 반응 버튼', type: 'toggle' },
  { key: 'reactions', label: '반응 이모지 (띄어쓰기로 구분)', type: 'strings', placeholder: '❤️ 🥹 😭 ✨ 👏' },
  { key: 'features.showViews', label: '조회수 보이기', type: 'toggle' },
  { key: 'features.nameSwap', label: '이름 변환 사용', type: 'toggle', help: '글 속 {{나}} {{상대}} {{페어}}를 프로필 이름으로 바꿔요.' },
  { key: 'postsPerPage', label: '한 페이지에 보일 글 수', type: 'number', min: 3, max: 60 },
]

const fontOptions = FONTS.map((f) => ({ value: f.key, label: f.label }))

export const PALETTE_KEYS = [
  { key: 'accent', label: '포인트 색' },
  { key: 'accentText', label: '포인트 위 글자색' },
  { key: 'bg', label: '배경' },
  { key: 'bg2', label: '배경 2 (그라데이션 끝)' },
  { key: 'surface', label: '카드' },
  { key: 'surface2', label: '카드 안쪽 / 입력칸' },
  { key: 'text', label: '글자' },
  { key: 'textSub', label: '보조 글자' },
  { key: 'line', label: '구분선' },
  { key: 'drawer', label: '서랍 메뉴 배경' },
  { key: 'memo', label: '메모지 배경' },
  { key: 'memoText', label: '메모지 글자' },
]

export const DESIGN_SECTIONS = [
  {
    key: 'background',
    label: '배경',
    icon: 'fa-solid fa-fill-drip',
    fields: [
      {
        key: 'bgType',
        label: '배경 종류',
        type: 'segmented',
        options: [
          { value: 'solid', label: '단색' },
          { value: 'gradient', label: '그라데이션' },
          { value: 'pattern', label: '패턴' },
          { value: 'image', label: '이미지' },
        ],
      },
      { key: 'bgAngle', label: '그라데이션 각도', type: 'range', min: 0, max: 360, unit: '°', show: (t) => t.bgType === 'gradient' },
      {
        key: 'pattern',
        label: '패턴',
        type: 'select',
        show: (t) => t.bgType === 'pattern',
        options: [
          { value: 'dots', label: '물방울' },
          { value: 'grid', label: '모눈' },
          { value: 'lines', label: '줄노트' },
          { value: 'diagonal', label: '사선' },
          { value: 'checker', label: '체크' },
          { value: 'hearts', label: '하트' },
          { value: 'stars', label: '별' },
        ],
      },
      { key: 'patternSize', label: '패턴 크기', type: 'range', min: 8, max: 60, unit: 'px', show: (t) => t.bgType === 'pattern' },
      { key: 'bgImage', label: '배경 이미지', type: 'image', guide: 'pageBg', show: (t) => t.bgType === 'image' },
      { key: 'bgImageDark', label: '다크 모드 배경 이미지 (선택)', type: 'image', guide: 'pageBg', show: (t) => t.bgType === 'image' },
      {
        key: 'bgFit',
        label: '이미지 채우기',
        type: 'segmented',
        show: (t) => t.bgType === 'image',
        options: [
          { value: 'cover', label: '꽉 채우기' },
          { value: 'contain', label: '전체 보이기' },
          { value: 'repeat', label: '반복' },
        ],
      },
      { key: 'bgBlur', label: '이미지 흐림', type: 'range', min: 0, max: 30, unit: 'px', show: (t) => t.bgType === 'image' },
      { key: 'bgOverlay', label: '배경색 덮기 (글씨 잘 보이게)', type: 'range', min: 0, max: 0.95, step: 0.05, show: (t) => t.bgType === 'image' },
    ],
  },
  {
    key: 'type',
    label: '글꼴',
    icon: 'fa-solid fa-font',
    fields: [
      { key: 'font', label: '본문 글꼴', type: 'select', options: fontOptions },
      { key: 'headingFont', label: '제목 글꼴', type: 'select', options: [{ value: 'same', label: '본문과 같게' }, ...fontOptions] },
      { key: 'customFontUrl', label: '직접 올린 글꼴 파일 (woff2/ttf)', type: 'image', accept: '.woff,.woff2,.ttf,.otf,font/*', help: '올린 뒤 위 글꼴에서 "직접 올린 글꼴"을 고르세요. 눈누 등에서 받은 웹폰트 주소를 붙여넣어도 돼요.' },
      { key: 'fontScale', label: '글자 크기', type: 'range', min: 0.8, max: 1.3, step: 0.02, unit: '배' },
      { key: 'titleWeight', label: '제목 굵기', type: 'range', min: 300, max: 900, step: 100 },
      { key: 'letterSpacing', label: '자간', type: 'range', min: -0.05, max: 0.1, step: 0.005, unit: 'em' },
      { key: 'lineHeight', label: '본문 줄 간격', type: 'range', min: 1.4, max: 2.4, step: 0.05 },
    ],
  },
  {
    key: 'shape',
    label: '모양',
    icon: 'fa-solid fa-shapes',
    fields: [
      {
        key: 'cardStyle',
        label: '카드 스타일',
        type: 'select',
        options: [
          { value: 'flat', label: 'One UI 기본 (평면)' },
          { value: 'shadow', label: '그림자' },
          { value: 'outline', label: '테두리' },
          { value: 'glass', label: '유리 (반투명 + 흐림)' },
          { value: 'soft', label: '말랑 (뉴모피즘)' },
          { value: 'sticker', label: '스티커 (진한 테두리 + 그림자)' },
        ],
      },
      { key: 'radius', label: '모서리 둥글기', type: 'range', min: 0, max: 40, unit: 'px' },
      { key: 'buttonShape', label: '버튼 모양', type: 'segmented', options: [{ value: 'pill', label: '알약' }, { value: 'rounded', label: '둥근 사각' }, { value: 'square', label: '각진' }] },
      { key: 'gap', label: '위젯 · 카드 간격', type: 'range', min: 4, max: 32, unit: 'px' },
      { key: 'contentWidth', label: '본문 최대 너비', type: 'range', min: 520, max: 1200, step: 10, unit: 'px' },
    ],
  },
  {
    key: 'layout',
    label: '배치',
    icon: 'fa-solid fa-table-columns',
    fields: [
      {
        key: 'headerStyle',
        label: '페이지 제목',
        type: 'segmented',
        options: [
          { value: 'expanded', label: 'One UI 큰 제목' },
          { value: 'compact', label: '작게' },
          { value: 'centered', label: '가운데' },
        ],
      },
      { key: 'expandedHeight', label: '큰 제목 영역 높이', type: 'range', min: 12, max: 50, unit: 'vh', show: (t) => t.headerStyle !== 'compact' },
      { key: 'homeTitle', label: '홈에도 사이트 이름 큰 제목 보이기', type: 'toggle' },
      {
        key: 'homeTitleBg',
        label: '홈 큰 제목 배경',
        type: 'segmented',
        show: (t) => t.homeTitle,
        options: [
          { value: 'none', label: '없음' },
          { value: 'card', label: '카드' },
          { value: 'glass', label: '반투명 유리' },
          { value: 'image', label: '이미지' },
        ],
        help: '사이트 배경 위에서 제목과 소개글이 잘 보이도록 뒤에 판을 깔아요.',
      },
      { key: 'homeTitleImage', label: '홈 제목 배경 이미지', type: 'image', guide: 'homeTitle', show: (t) => t.homeTitle && t.homeTitleBg === 'image' },
      { key: 'homeTitleDim', label: '이미지 위 어둡게 (글자 잘 보이게)', type: 'range', min: 0, max: 0.8, step: 0.05, show: (t) => t.homeTitle && t.homeTitleBg === 'image' },
      {
        key: 'topbarStyle',
        label: '상단바 배경',
        type: 'segmented',
        options: [
          { value: 'blur', label: '반투명 흐림' },
          { value: 'solid', label: '불투명' },
          { value: 'transparent', label: '투명' },
        ],
      },
      { key: 'topbarOpacity', label: '상단바 배경 진하기', type: 'range', min: 0, max: 100, unit: '%', show: (t) => t.topbarStyle === 'blur' },
      {
        key: 'contentFrame',
        label: '본문 창 (인터넷 창 모양 배경)',
        type: 'segmented',
        options: [
          { value: 'auto', label: '배경이 사진·패턴일 때만' },
          { value: 'always', label: '항상' },
          { value: 'never', label: '안 씀' },
        ],
        help: '사이트 배경 위에 글자가 잘 보이도록 본문을 브라우저 창 모양 판 위에 올려요.',
      },
      { key: 'frameOpacity', label: '본문 창 진하기', type: 'range', min: 30, max: 100, unit: '%', show: (t) => t.contentFrame !== 'never' },
      { key: 'frameBar', label: '본문 창 위쪽 주소창 보이기', type: 'toggle', show: (t) => t.contentFrame !== 'never' },
      { key: 'frameOnHome', label: '홈 화면에도 본문 창 쓰기', type: 'toggle', show: (t) => t.contentFrame !== 'never' },
      {
        key: 'navStyle',
        label: '메뉴',
        type: 'segmented',
        options: [
          { value: 'drawer', label: '서랍' },
          { value: 'bottom', label: '하단 탭' },
          { value: 'both', label: '둘 다' },
        ],
      },
      { key: 'drawerSide', label: '서랍 위치', type: 'segmented', options: [{ value: 'left', label: '왼쪽' }, { value: 'right', label: '오른쪽' }], show: (t) => t.navStyle !== 'bottom' },
      { key: 'homeLayout', label: '홈 화면 페이지', type: 'segmented', options: [{ value: 'swipe', label: '옆으로 넘기기' }, { value: 'stack', label: '아래로 이어보기' }] },
      {
        key: 'dots',
        label: '페이지 표시',
        type: 'segmented',
        show: (t) => t.homeLayout !== 'stack',
        options: [
          { value: 'pill', label: '알약' },
          { value: 'dot', label: '점' },
          { value: 'line', label: '선' },
          { value: 'number', label: '숫자' },
          { value: 'none', label: '없음' },
        ],
      },
      { key: 'dotsPosition', label: '페이지 표시 위치', type: 'segmented', show: (t) => t.homeLayout !== 'stack' && t.dots !== 'none', options: [{ value: 'bottom', label: '아래' }, { value: 'top', label: '위' }] },
    ],
  },
  {
    key: 'list',
    label: '목록',
    icon: 'fa-solid fa-list',
    fields: [
      { key: 'listStyle', label: '기본 목록 모양 (카테고리별로 따로 정할 수도 있어요)', type: 'select', options: LIST_STYLES, help: '방문자는 목록 모양을 바꿀 수 없고, 여기서 정한 모양으로만 보여요.' },
      { key: 'noticeStyle', label: '공지사항 목록 모양', type: 'select', options: LIST_STYLES },
      { key: 'galleryColumns', label: '갤러리 열 수', type: 'range', min: 2, max: 5 },
      { key: 'showThumbs', label: '썸네일 보이기', type: 'toggle' },
      { key: 'showExcerpt', label: '요약 보이기', type: 'toggle' },
    ],
  },
  {
    key: 'effects',
    label: '효과 · 모드',
    icon: 'fa-solid fa-wand-magic-sparkles',
    fields: [
      { key: 'mode', label: '처음 방문했을 때 화면', type: 'segmented', options: [{ value: 'auto', label: '기기 설정 따라' }, { value: 'light', label: '라이트' }, { value: 'dark', label: '다크' }] },
      { key: 'allowToggle', label: '방문자가 라이트/다크 바꿀 수 있게', type: 'toggle' },
      { key: 'animations', label: '애니메이션', type: 'toggle' },
      { key: 'hoverLift', label: '마우스를 올리면 살짝 떠오르기', type: 'toggle' },
    ],
  },
  {
    key: 'cursor',
    label: '커서',
    icon: 'fa-solid fa-arrow-pointer',
    fields: [
      {
        key: 'cursor',
        label: '마우스 커서',
        type: 'select',
        options: [
          { value: 'default', label: '기본 (컴퓨터 설정)' },
          { value: 'heart', label: '하트' },
          { value: 'star', label: '별' },
          { value: 'paw', label: '발바닥' },
          { value: 'sparkle', label: '반짝이' },
          { value: 'custom', label: '직접 올린 이미지' },
        ],
        help: '모양 커서는 포인트 색으로 칠해지고, 링크 위에서는 살짝 커져요. 휴대폰에서는 보이지 않아요.',
      },
      { key: 'cursorSize', label: '커서 크기', type: 'range', min: 16, max: 48, unit: 'px', show: (t) => !['default', 'custom'].includes(t.cursor) },
      {
        key: 'cursorImage',
        guide: 'cursor',
        label: '기본 커서 이미지',
        type: 'image',
        accept: 'image/png,image/gif,image/svg+xml,.cur,.ico',
        uploadOptions: { maxSize: 32, keepPng: true },
        help: 'PNG를 올리면 32px로 자동으로 줄여요. 32×32 이하 투명 배경 PNG나 .cur 파일이 가장 잘 보여요.',
        show: (t) => t.cursor === 'custom',
      },
      { key: 'cursorX', label: '클릭 지점 X (왼쪽에서 px)', type: 'range', min: 0, max: 32, show: (t) => t.cursor === 'custom' },
      { key: 'cursorY', label: '클릭 지점 Y (위에서 px)', type: 'range', min: 0, max: 32, show: (t) => t.cursor === 'custom' },
      {
        key: 'cursorPointerImage',
        guide: 'cursor',
        label: '링크 위 커서 이미지 (비우면 기본 커서와 같게)',
        type: 'image',
        accept: 'image/png,image/gif,image/svg+xml,.cur,.ico',
        uploadOptions: { maxSize: 32, keepPng: true },
        show: (t) => t.cursor === 'custom',
      },
      { key: 'cursorPointerX', label: '링크 커서 클릭 지점 X', type: 'range', min: 0, max: 32, show: (t) => t.cursor === 'custom' && t.cursorPointerImage },
      { key: 'cursorPointerY', label: '링크 커서 클릭 지점 Y', type: 'range', min: 0, max: 32, show: (t) => t.cursor === 'custom' && t.cursorPointerImage },
    ],
  },
  {
    key: 'css',
    label: '사용자 CSS',
    icon: 'fa-solid fa-code',
    fields: [
      {
        key: 'customCss',
        label: 'CSS 직접 입력',
        type: 'html',
        rows: 14,
        help: '가장 마지막에 적용돼서 무엇이든 덮어쓸 수 있어요. 예) .widget { border: 2px dashed var(--accent); }  ·  주요 변수: --accent, --bg, --surface, --text, --radius',
      },
    ],
  },
]

export const BANNER_FIELDS = [
  { type: 'heading', label: '배너 게시판', help: '메뉴의 "배너"에서 보이는 페이지예요.' },
  { key: 'bannerIntro', label: '안내 문구' },
  { type: 'heading', label: '우리 배너', help: '다른 사람이 퍼갈 수 있게 HTML 코드와 함께 보여줘요.' },
  { key: 'myBanner.image', label: '배너 이미지', type: 'image', guide: 'linkBanner', uploadOptions: { maxSize: 600, keepPng: true }, help: '흔히 200×40, 88×31 같은 작은 크기를 써요. GIF 움짤도 그대로 올라가요.' },
  { key: 'myBanner.url', label: '연결 주소 (비우면 이 사이트)' },
  { key: 'myBanner.alt', label: '대체 문구' },
  { key: 'myBanner.note', label: '안내 (예: 직링크 금지, 퍼가실 땐 방명록에 알려주세요)', type: 'textarea', rows: 2 },
  { type: 'heading', label: '링크 배너' },
  {
    key: 'banners',
    label: '배너 목록',
    type: 'list',
    itemLabel: '배너',
    itemFields: [
      { key: 'image', label: '배너 이미지', type: 'image', guide: 'linkBanner', uploadOptions: { maxSize: 600, keepPng: true } },
      { key: 'name', label: '이름' },
      { key: 'url', label: '연결 주소' },
      { key: 'desc', label: '한 줄 설명' },
    ],
  },
]

export const PAGE_FIELDS = [
  { type: 'heading', label: '안내', help: '비워두면 기본 문구가 보여요. 문구에는 HTML과 {{나}} {{상대}} {{페어}}를 쓸 수 있어요. 예) <b>굵게</b>, <span style="color:hotpink">색</span>, <br> 줄바꿈' },
  { type: 'heading', label: '캘린더' },
  { key: 'pages.calendar.title', label: '제목', placeholder: '캘린더' },
  { key: 'pages.calendar.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '날짜별로 모아보는 우리의 기록' },
  { key: 'pages.calendar.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.calendar.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.calendar.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.calendar.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { key: 'pages.calendar.listTitle', label: '달력 아래 목록 제목 ({년} {월} 사용 가능, 띄어쓰기 한 칸이면 숨김)', placeholder: '{년}년 {월}월의 기록' },
  { type: 'heading', label: '전체 기록' },
  { key: 'pages.archive.title', label: '제목', placeholder: '전체 기록' },
  { key: 'pages.archive.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '(글 수가 자동으로 표시돼요)' },
  { key: 'pages.archive.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.archive.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.archive.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.archive.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { type: 'heading', label: '공지사항' },
  { key: 'pages.notice.title', label: '제목', placeholder: '공지사항' },
  { key: 'pages.notice.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '(글 수가 자동으로 표시돼요)' },
  { key: 'pages.notice.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.notice.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.notice.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.notice.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { type: 'heading', label: '방명록' },
  { key: 'pages.guestbook.title', label: '제목', placeholder: '방명록' },
  { key: 'pages.guestbook.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '(관리 › 사이트의 방명록 안내 문구)' },
  { key: 'pages.guestbook.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.guestbook.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.guestbook.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.guestbook.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { type: 'heading', label: '태그' },
  { key: 'pages.tags.title', label: '제목', placeholder: '태그 모음' },
  { key: 'pages.tags.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '(태그 수가 자동으로 표시돼요)' },
  { key: 'pages.tags.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.tags.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.tags.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.tags.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { type: 'heading', label: '배너' },
  { key: 'pages.banners.title', label: '제목', placeholder: '배너' },
  { key: 'pages.banners.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '(배너 게시판의 안내 문구)' },
  { key: 'pages.banners.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.banners.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.banners.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.banners.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
  { type: 'heading', label: '검색' },
  { key: 'pages.search.title', label: '제목', placeholder: '검색' },
  { key: 'pages.search.subtitle', label: '아래 문구 (HTML 가능)', type: 'textarea', rows: 2, placeholder: '' },
  { key: 'pages.search.eyebrow', label: '제목 위 작은 글씨 (HTML 가능)' },
  { key: 'pages.search.hideSubtitle', label: '아래 문구 숨기기', type: 'toggle' },
  { key: 'pages.search.align', label: '정렬', type: 'segmented', options: [{ value: '', label: '디자인 설정 따라' }, { value: 'left', label: '왼쪽' }, { value: 'center', label: '가운데' }] },
  { key: 'pages.search.image', label: '제목 위 이미지 (선택)', type: 'image', guide: 'pageHeader' },
]
